
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TopNavigation from './top-navigation'

//client component 
import  SessionProvider from './components/SessionProvider'
//server side session
import { getServerSession } from 'next-auth'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <TopNavigation />
          <main>
          {children}
          </main>
            </SessionProvider>
          </body>
    </html>
  )
}
